### ISSUE TITLE
Suggestion: add a lock-inventory option (true/false) for menu configs

### ISSUE THREAD

**Issue by featxeven** [AkisYTB3/NotionMenus#3]
**true:** Players can move items in their inventory.

**false:** Inventory item movement is disabled (items are locked).

Example of how it could look like:
```
id: menu
title: Menu
command: menu
lock-inventory: true // <- Here
size: 45
items:
  ...
```

**Comment by YeahAkis** [comment]
Thank you for the suggestion!
Added it, defaults to true
example:

```yml
id: locked_inv
title: Locked Inventory
lock-inventory: true # makes it so people can't move items in their inventory
```
